baseURL = 'https://touchouss.lol/'
languageCode = 'fr-be'
title = "Les Tou'Chouss"
theme = "loficode"

# Enable emoji support
enableEmoji = true

# Output formats for SPA functionality
[outputs]
  home = ["HTML", "JSON", "RSS", "pages"]
  page = ["HTML"]
  section = ["HTML"]

# Custom output formats
[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
  [outputFormats.pages]
    mediaType = "application/json"
    baseName = "pages"
    isPlainText = true

# Pagination
[pagination]
  pagerSize = 6
  path = "page"

[params]
  description = "Troupe d'improvisation théâtrale basée à Liège" 

  [params.author]
  # author section
  name= "Les Tou'Chouss"
  image = "images/profile.png"

  # Profile section
  [params.profile]
    name = "Les Tou'Chouss"
    tagline = "Tout en finesse"
    photo = "images/profile.png"

  # Social links - Supported platforms: github, twitter, linkedin, email, mastodon, youtube, instagram, facebook
  [params.social]
    #github = "raisingpixels"
    #twitter = "raisingpixels"
    # linkedin = "your-linkedin-username"
    email = "lestouchouss@gmail.com"
    # mastodon = "https://mastodon.social/@yourusername"
    # youtube = "https://youtube.com/@yourusername"
    instagram = "https://www.instagram.com/lestouchouss"
    facebook = "https://www.facebook.com/touchoussimpro"
    rss = "/index.xml"

# Navigation menu

[[menu.main]]
  name = "Spectacles"
  url = "/event/"
  weight = 10

[[menu.main]]
  name = "L'équipe"
  url = "/about/"
  weight = 20

[[menu.main]]
name = "Photos"
url = "/photos/"
weight = 30

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 40

[[menu.main]]
  name = "Voter"
  url = "/vote/"
  weight = 50

# Github actions
[caches]
  [caches.images]
    dir = ':cacheDir/images'
